# 6.4.4.2 Retrieve the value of a property
# GET {wt}/properties/{acceleration}

# we assume property name === action name (in fact, there is NO property_name)
GET {{IOT_EMULATOR}}/1/properties/action_name1
user: user
password: password

###


GET {{IOT_EMULATOR}}/9/properties/action_name2
user: user
password: password

###
