#POST {wt}/actions/reboot

### MUST WORK
POST localhost:8001/1/actions/action_name1
Content-Type: application/json
user: user
password: password


{
  "action_name1":"new_property_value"
}

### MUST FAIL
POST localhost:8001/1/actions/action_name1
Content-Type: application/json
user: user
password: password


{
  "INFORRECT_action_name":"new_property_value"
}

###

# MUST fail invalid action in url
POST localhost:8001/1/actions/BADaction_name1
Content-Type: application/json
user: user
password: password


{
  "action_name1":"new_property_value"
}

###


# MUST fail invalid action in payload
POST localhost:8001/1/actions/action_name1
Content-Type: application/json
user: user
password: password


{
  "BADaction_name1":"new_property_value"
}

###