# http POST ${IOT_EMULATOR}/create user:user password:password <<< '{ "name": "jsonName", "brand":"jsonBrand", "links": { "properties":[ {"action_name1":"property_value1"}, {"action_name2":"property_value2"} ], "actions":["action_name1","action_name2"] } }'

POST {{IOT_EMULATOR}}/create
Content-Type: application/json
user: user
password: password

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"property_name1":"property_value1"},
      {"property_name2":"property_value2"}
    ],
    "actions":["property_name1","property_name2"]
  }
}

###