index:
    path: /
    controller: App\Infrastructure\ThingController::index
    methods: GET

search:
    path: /{id}
    controller: App\Infrastructure\ThingController::search
    methods: POST
    requirements:
      id: '\d+'

delete:
    path: /{id}
    controller: App\Infrastructure\ThingController::delete
    methods: DELETE

create:
    path: /create
    controller: App\Infrastructure\ThingController::create