index:
    path: /
    controller: App\Infrastructure\ThingController::index
    methods: GET

search:
    path: /{id}
    controller: App\Infrastructure\ThingController::search
    methods: GET
    requirements:
      id: '\d+'

delete:
    path: /{id}
    controller: App\Infrastructure\ThingController::delete
    methods: DELETE

create:
    path: /create
    controller: App\Infrastructure\ThingController::create
    methods: POST

update_property:
    path: /{id}/properties/{action_name}
    controller: App\Infrastructure\ThingController::updateProperty
    methods: PUT
    requirements:
        id: '\d+'
