index:
    path: /
    controller: App\Infrastructure\ThingController::index
    methods: GET

search:
    path: /{id}
    controller: App\Infrastructure\ThingController::search
    methods: GET
    requirements:
      id: '\d+'

delete_thing:
    path: /{id}
    controller: App\Infrastructure\ThingController::delete
    methods: DELETE

create:
    path: /create
    controller: App\Infrastructure\ThingController::create
    methods: POST

# post an actions
execute_action:
    path: /{id}/actions/{action_name}
    controller: App\Infrastructure\ThingController::executeAction
    methods: POST
    requirements:
        id: '\d+'

get_value_of_property:
    path: /{id}/properties/{property_name}
    controller: App\Infrastructure\ThingController::getValueOfProperty
    methods: GET

get_actions:
    path: /{id}/actions
    controller: App\Infrastructure\ThingController::getActionsByThingId
    methods: GET
    requirements:
      id: '\d+'