# D=> dircect connectivity
#
#    REST URL 	                        POST 	GET 	PUT 	DELETE 	OPTIONS 	Details
#       /                                       D                               List of things                UNICO sin credenciales
#      {wt} 	                        G,C 	D,G,C 	D,G,C 	G,C 	D,G,C 	Thing Resource
#      {wt}/model 	                    - 	    D,G,C 	G,C 	- 	    D,G,C 	Model Resource
#      {wt}/properties 	                G,C 	D,G,C 	- 	    - 	    D,G,C 	Properties Resource
#      {wt}/properties/{id} 	        - 	    D,G,C 	G,C 	- 	    D,G,C 	Properties Resource
#      {wt}/actions 	                G,C 	D,G,C 	- 	    - 	    D,G,C 	Actions Resource
#      {wt}/actions/{id} 	            D,G,C 	D,G,C 	- 	    - 	    D,G,C 	Actions Resource
#      {wt}/actions/{id}/{actionId} 	- 	    D,G,C 	- 	    D,G,C 	D,G,C 	Actions Resource
#      {wt}/things 	                    G,C 	G,C 	- 	    - 	    G,C 	Things Resource
#      {wt}/things/{id} 	            - 	    G,C 	G,C 	G,C 	G,C 	Things Resource
#      {wt}/subscriptions 	            - 	    D,G,C 	- 	    D,G,C 	D,G,C 	Subscriptions Resource

index:
    path: /
    controller: App\Infrastructure\ThingController::index
    methods: GET

# no need for credentials
get_thing:
    path: /{id}
    controller: App\Infrastructure\ThingController::getThing
    methods: GET
    requirements:
      id: '\d+'


delete_thing:
    path: /{id}
    controller: App\Infrastructure\ThingController::delete
    methods: DELETE


create:
    path: /create
    controller: App\Infrastructure\ThingController::create
    methods: POST

# post an actions
execute_action:
    path: /{id}/actions/{action_name}
    controller: App\Infrastructure\ThingController::executeAction
    methods: POST
    requirements:
        id: '\d+'

get_value_of_property:
    path: /{id}/properties/{property_name}
    controller: App\Infrastructure\ThingController::getValueOfProperty
    methods: GET

# credentials needed
get_actions:
    path: /{id}/actions
    controller: App\Infrastructure\ThingController::getActionsByThingId
    methods: GET
    requirements:
      id: '\d+'


fallback_route:
    path: /{url}
    controller: App\Infrastructure\FallbackController::fallback
