index:
    path: /
    controller: App\Infrastructure\ThingController::index
    methods: GET

search:
    path: /{id}
    controller: App\Infrastructure\ThingController::search
    methods: GET
    requirements:
      id: '\d+'

delete:
    path: /{id}
    controller: App\Infrastructure\ThingController::delete
    methods: DELETE

create:
    path: /create
    controller: App\Infrastructure\ThingController::create
    methods: POST

# post an actions
execute_action:
    path: /{id}/actions/{action_name}
    controller: App\Infrastructure\ThingController::executeAction
    methods: PUT
    requirements:
        id: '\d+'

# hay que hacer un GET properties/property_name


getActions:
    path: /{id}/actions
    controller: App\Infrastructure\ThingController::getActionsByThingId
    methods: GET
    requirements:
      id: '\d+'
