POST http://localhost:8000/create
Content-Type: application/json
user: user
password: password

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"jsonAction1":"jsonActionValue1"},
      {"jsonAction2":"jsonActionValue2"}
    ],
    "actions":["jsonAction2"]
  }
}

###
