#POST {wt}/actions/reboot

POST localhost:8000/1/actions/jsonAction2
Content-Type: application/json


{
  "jsonAction2":"nuevoValor6"
}

###

# MUST fail invalid action in url
POST localhost:8000/1/actions/BADjsonAction1
Content-Type: application/json


{
  "jsonAction1":"nuevoValor"
}

###


# MUST fail invalid action in payload
POST localhost:8000/1/actions/jsonAction1
Content-Type: application/json


{
  "BADjsonAction1":"nuevoValor"
}

###