# PUT {wt}/properties/temperature/

PUT localhost:8000/1/properties/jsonAction1
Content-Type: application/json

[
{
"jsonAction1":"nuevoValor"
}
]
###

# MUST fail invalid action in url
PUT localhost:8000/1/properties/BADjsonAction1
Content-Type: application/json

[
  {
    "jsonAction1":"nuevoValor"
  }
]
###


# MUST fail invalid action in payload
PUT localhost:8000/1/properties/jsonAction1
Content-Type: application/json

[
  {
    "BADjsonAction1":"nuevoValor"
  }
]
###