POST {{IOT_EMULATOR}}/create
Content-Type: application/json
user: user
password: password

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"action_name1":"action_nameValue1"},
      {"action_name2":"action_nameValue2"}
    ],
    "actions":["action_name2"]
  }
}

###
