GET http://localhost:8000/
Accept: */*
Cache-Control: no-cache

<> 2018-11-29T074844.200.json

###

GET http://localhost:8000/1
Accept: */*
Cache-Control: no-cache

<> 2018-11-29T074844.200.json

###

DELETE http://localhost:8000/1

###

GET http://localhost:8000/create
Content-Type: application/json

{
"brand":"jsonBrand",
"actions":["jsonAction1","jsonAction2"]
}
###

