GET http://localhost:8000/
Accept: */*
Cache-Control: no-cache

<> 2018-11-29T074844.200.json

###

GET http://localhost:8000/1
Accept: */*
Cache-Control: no-cache

<> 2018-11-29T074844.200.json

###

DELETE http://localhost:8000/1

### (must Work)

POST http://localhost:8000/create
Content-Type: application/json

{
  "name": "jsonName",
"brand":"jsonBrand",
"links":
{
  "properties":[
    {"jsonAction1":"jsonActionValue1"},
    {"jsonAction2":"jsonActionValue2"}
  ],
  "actions":["jsonAction1","jsonAction2"]
}
}

###  Desordenado (must Work pero no funciona por ahora)

POST http://localhost:8000/create
Content-Type: application/json

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"jsonAction2":"jsonActionValue2"},
      {"jsonAction1":"jsonActionValue1"}
    ],
    "actions":["jsonAction1","jsonAction2"]
  }
}


### Falta 1 propiedad

POST http://localhost:8000/create
Content-Type: application/json

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"jsonAction2":"jsonActionValue2"}
    ],
    "actions":["jsonAction1","jsonAction2"]
  }
}

### Sobra 1 propiedad

POST http://localhost:8000/create
Content-Type: application/json

{
  "name": "jsonName",
  "brand":"jsonBrand",
  "links":
  {
    "properties":[
      {"jsonAction1":"jsonActionValue1"},
      {"jsonAction2":"jsonActionValue2"},
      {"jsonAction3Sobra":"jsonActionValue3Sobra"}
    ],
    "actions":["jsonAction1","jsonAction2"]
  }
}


###  Bad json

POST http://localhost:8000/create
Content-Type: application/json

{
  "bad json":
}
###

# SIN NAME
POST http://localhost:8000/create
Content-Type: application/json

{
  "brand":"jsonBrand",
  "links":
  {
    "actions":["jsonAction1","jsonAction2"]
  }
}

###

# SIN BRAND
POST http://localhost:8000/create
Content-Type: application/json

{
  "name":"jsonName",
  "links":
  {
    "actions":["jsonAction1","jsonAction2"]
  }
}

###





